name: flutter_pd_example
description: Demonstrates how to use the flutter_pd plugin.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_pd:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/pd-patches/main/microphone_level.pd
    - assets/pd-patches/main/simple_sin.pd
    - assets/pd-patches/main/simple_sin_with_volume.pd
    - assets/pd-patches/main/soundfile_player.pd
    - assets/audio/falling.wav
